import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-white">
          <nav className="flex justify-evenly justify-items-end text-2xl p-2 font-bold h-4 border-xl">
            <Link href="/">Home</Link>
            <Link href="/tasks">Tasks</Link>
            <Link href="/stats">Stats</Link>
            <Link href="/settings">Settings</Link>
          </nav>
          {children}
        </div>
      </body>
    </html>
  );
}
